DROP TABLE PROFESSORES;
DROP TABLE SEMESTRES;
DROP TABLE PROFESSORES;
DROP TABLE CURSOS;
DROP TABLE DISCIPLINAS;
DROP TABLE TURMAS;
DROP TABLE ALOCACOES;
-- \************************************************************\

CREATE TABLE PROFESSORES
   (
	  CODIGO INTEGER NOT NULL , 	
      NOME VARCHAR(50) NOT NULL
	       
   );

ALTER TABLE PROFESSORES
   ADD CONSTRAINT PROFESSORES_PK Primary Key (
      CODIGO);

-- \************************************************************\

CREATE TABLE SEMESTRES
   (
	  DESCRICAO VARCHAR(20) NOT NULL
	       
   );

ALTER TABLE SEMESTRES
   ADD CONSTRAINT DESCRICAO_PK Primary Key (
      DESCRICAO);

-- \************************************************************\
CREATE TABLE CURSOS
   (
	  CODIGO INTEGER NOT NULL , 	
      NOME VARCHAR(30) NOT NULL
	       
   );

ALTER TABLE CURSOS
   ADD CONSTRAINT CURSOS_PK Primary Key (
      CODIGO);

-- \************************************************************\
CREATE TABLE DISCIPLINAS
   (
	  CODIGO INTEGER NOT NULL , 	
      NOME VARCHAR(40) NOT NULL
	       
   );

ALTER TABLE DISCIPLINAS
   ADD CONSTRAINT DISCIPLINAS_PK Primary Key (
      CODIGO);


-- \************************************************************\
CREATE TABLE TURMAS
   (
	  CODIGO INTEGER NOT NULL , 	
      NOME VARCHAR(20) NOT NULL,
	  CODIGO_DISCIPLINA INTEGER NOT NULL
	       
   );

ALTER TABLE TURMAS
   ADD CONSTRAINT TURMAS_PK Primary Key (
      CODIGO);
	  
ALTER TABLE TURMAS
   ADD CONSTRAINT DISCIPLINAS_FK Foreign Key (
      CODIGO_DISCIPLINA)
   REFERENCES DISCIPLINAS (
      CODIGO);

-- \************************************************************\
CREATE TABLE ALOCACOES
   (
	  CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 	
      CODIGO_PROFESSOR INTEGER NOT NULL,
	  CODIGO_TURMA INTEGER NOT NULL,
	  CODIGO_DISCIPLINA INTEGER NOT NULL
   );

ALTER TABLE ALOCACOES
   ADD CONSTRAINT ALOCACAO_PK Primary Key (CODIGO);

ALTER TABLE ALOCACOES
   ADD CONSTRAINT PROFESSORES_FK Foreign Key (CODIGO_PROFESSOR)
   REFERENCES PROFESSORES (CODIGO);

ALTER TABLE ALOCACOES
   ADD CONSTRAINT TURMAS_FK Foreign Key (CODIGO_TURMA)
   REFERENCES TURMAS (CODIGO);
	  
ALTER TABLE ALOCACOES
   ADD CONSTRAINT DISCIPLINA_FK Foreign Key (CODIGO_DISCIPLINA)
   REFERENCES DISCIPLINAS (CODIGO);
	  
/* ALTER TABLE ALOCACOES
   ADD CONSTRAINT ALOCACOES_UNQ_CD Unique (
      CODIGO_PROFESSOR, CODIGO_TURMA);
 */	  
